### ISSUE TITLE
My issue test

### ISSUE THREAD

**Issue by LDong-Arm** [ARMmbed/github-to-jira-test#55]
### Description of defect

Test the new issue triaging script for GitHub Actions.

#### Target(s) affected by this defect ?

N/A

#### Toolchain(s) (name and version) displaying this defect ?

N/A

#### What version of Mbed-os are you using (tag or sha) ?

mbed-os-6.10.0

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)

N/A

#### How is this defect reproduced ? 

N/A

**Comment by mbedmain** [comment]
@LDong-Arm thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'. This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information.
